### ISSUE TITLE
Unable to print variables using sc_printf

### ISSUE THREAD

**Issue by deepeshsahoo** [syntacore/scr1#23]
#include "sc_print.h"
#include<stdlib.h>
int main()
{
    sc_printf("Entering Pointer Bounds Check!\n");
    int* ptr = malloc(10 * sizeof(int));
    for(int i = 0; i < 10; i++){
    	ptr[i] = i;
    }
    int x = ptr[100];
    sc_printf("X : %d", x);            // Leads to an error _sbrk_r gcc undefined
    sc_printf("Bounds Check Complete!\n");
    return 0;
}

In the above code, the sc_printf("%d", var_name) shows errors and doesn't generate the result.

**Comment by eb-sc** [comment]
Hello,

The problem is in "malloc", which we currently don't support in the project. All of our sample tests build and run successfully with the current setup.

However, you can experiment with the project. For example, you can try configuring linking flags (LDFLAGS in the /sim/tests/common/common.mk) by including linking for standard libraries (remove the -nostdlib flag). We managed to run your example with such a setting, but we don't guarantee that it completely solves the problem.
