### ISSUE TITLE
Theoretical value of tcm performance improvement

### ISSUE THREAD

**Issue by snlkah** [syntacore/scr1#40]
I would like to know how much the SCR1 core can improve with tcm function than without tcm function under the same compiler conditions. Is there a theoretical value, such as Dhrystone score comparison?

**Comment by achuykov-sc** [comment]
Hi @snlkah,

I had run Dhrystone on SCR1 on Nexus A7 board. The Nexus A7 board is based on same FPGA chip as ARTY A7-**100T**. The FPGA image supports TCM, DDR and on-chip RAM. The switching from TCM to external memory is dramatical: 
* TCM -> DDR, the difference is more than x20 
* TCM -> On-chip RAM, the difference is more than x10
The difference is expected because of cache absence, specifics of implementation of the DDR controller and on-chip memory controller, and memory latency. 

The Dhrystone was built for high performance (`-O2`) and no-inlining (because of Dhrystone rules).  

BR,
Alexander
