### ISSUE TITLE
Incorrect linker flags' order into make file

### ISSUE THREAD

**Issue by russmakse** [syntacore/scr1#60]
I tried to build version 2023.09 but the test "dhrystone2" failed

![Screenshot from 2024-02-29 20-04-12](https://github.com/syntacore/scr1/assets/58990220/8c24b3e0-18c2-4e85-8009-825958e08431)

Changes

![Screenshot from 2024-03-01 00-24-17](https://github.com/syntacore/scr1/assets/58990220/8aca9336-ca37-4473-b2df-19eb08b25cd6)

**Comment by achuykov-sc** [comment]
Hi @russmakse,

Let me apologize for inconvenience in 2023.09. It is known issue. And it is fixed in 2024.02, please update your repo. 

If you would to fix it manually, please follow this guide (but it fixes only **this issue**). Open `sim/tests/common/common.mk` and add `--specs=nano.specs` to the line 15:
```
LDFLAGS   ?= -nostartfiles -nostdlib -lc -lgcc -march=rv32$(ARCH)_zicsr_zifencei -mabi=$(ABI) --specs=nano.specs
```

Best regards,
Alexander
